FROM node:14.15.3-alpine3.12

LABEL maintainer "ayuzaka <ayuzaka.f@gmail.com>"

WORKDIR /var/www/html/time-tracker
RUN apk add --update-cache vips-dev
RUN rm -rf node_modules && yarn install

CMD ["yarn", "dev"]
